//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AvailableTripTemporary
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Required field")]
        public int CodeVolunteer { get; set; }

        [StringLength(10,ErrorMessage = "Too long")]
        [Required(ErrorMessage = "Required field")]
        public string day { get; set; }

        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Time,ErrorMessage = "The time is not valid")]
        public Nullable<System.TimeSpan> StartTime { get; set; }

        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Time,ErrorMessage = "The time is not valid")]
        public Nullable<System.TimeSpan> FinishTime { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50,ErrorMessage = "Too long")]
        public string AddressSource { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50,ErrorMessage = "Too long")]
        public string City { get; set; }

        [Required(ErrorMessage = "Required field")] 
        public Nullable<int> NumOfSeats { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
    }
}
