//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Collections.Generic;
   

    public partial class ExecutedTrips
    {
        public int Id { get; set; }
        public Nullable<int> CodeRequest { get; set; }
        public Nullable<int> CodeVolunteer { get; set; }
    
        public virtual Volunteer Volunteer { get; set; }
        public virtual Request Request { get; set; }
    }
}
