//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDarkeyMiriamEntities : DbContext
    {
        public DBDarkeyMiriamEntities()
            : base("name=DBDarkeyMiriamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailableTrip> AvailableTrip { get; set; }
        public virtual DbSet<AvailableTripTemporary> AvailableTripTemporary { get; set; }
        public virtual DbSet<CodeStatus> CodeStatus { get; set; }
        public virtual DbSet<ExecutedTrips> ExecutedTrips { get; set; }
        public virtual DbSet<NotExecutedTrips> NotExecutedTrips { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<UsersPassword> UsersPassword { get; set; }
        public virtual DbSet<Volunteer> Volunteer { get; set; }
        public virtual DbSet<Request> Request { get; set; }
    }
}
