//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required field")]
        //[StringLength(9, MinimumLength = 9, ErrorMessage = "The Id is not valid")]
        public int IdPatient { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(9, ErrorMessage = "Too long")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "The phone is not valid")]
        public string Telephone { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(10, ErrorMessage = "Too long")]
        [RegularExpression(@"[0-9]+", ErrorMessage = "The phone is not valid")]
        public string Pelephone { get; set; }

        [Required(ErrorMessage = "Required field")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
