//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.ExecutedTrips = new HashSet<ExecutedTrips>();
            this.NotExecutedTrips = new HashSet<NotExecutedTrips>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateRequest_ { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Required field")]
        public Nullable<System.DateTime> CurrentDate { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string City { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string AddressSource { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string AddressDestination { get; set; }

        [Required(ErrorMessage = "Required field")]
        public Nullable<int> NumOfSeats { get; set; }

        [StringLength(10, ErrorMessage = "Too long")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "The phone is not valid")]
        public string AdditionalPelephone { get; set; }

        [Required(ErrorMessage = "Required field")]
        public Nullable<int> CodePatient { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(10, ErrorMessage = "Too long")]
        public string day { get; set; }

        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Time, ErrorMessage = "The time is not valid")]
        public Nullable<System.TimeSpan> hour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutedTrips> ExecutedTrips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotExecutedTrips> NotExecutedTrips { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
