//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersPassword
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required field")]
        [DataType(DataType.Password, ErrorMessage = "The password is not valid")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Required field")]
        public int CodeStatus { get; set; }
    
        public virtual CodeStatus CodeStatus1 { get; set; }
    }
}
