//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkeyMiriam0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volunteer()
        {
            this.AvailableTrip = new HashSet<AvailableTrip>();
            this.AvailableTripTemporary = new HashSet<AvailableTripTemporary>();
            this.ExecutedTrips = new HashSet<ExecutedTrips>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        //[RegularExpression(@"^[a-zA-Z]+$",ErrorMessage ="onlychars")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required field")]
        [RegularExpression(@"^(\d{9})$", ErrorMessage = "The Id is not valid")]
        public int IdVolunteer { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(9, ErrorMessage = "Too long")]
        [RegularExpression(@"^(\d{9})$", ErrorMessage = "The phone is not valid")]
        public string Telephone { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(10, ErrorMessage = "Too long")]
        [RegularExpression(@"^(\d{9})$", ErrorMessage = "The phone is not valid")]
        public string Pelephone { get; set; }

        [Required(ErrorMessage = "Required field")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Required field")]
        [StringLength(50, ErrorMessage = "Too long")]
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableTrip> AvailableTrip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableTripTemporary> AvailableTripTemporary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutedTrips> ExecutedTrips { get; set; }
    }
}
